first commit for js
Y0less/project-9FastDev pull request #9
Opened 2023-08-03 16:42 UTC by ValentynaJasochka

2023-08-03 17:47 UTC, sili41995 approved these changes

2023-08-04 07:48 UTC, Y0less requested changes
потрібно оновити гілку з main і впровадити викорискання API

2023-08-05 13:03 UTC, sili41995 approved these changes
1) categories. cursor pointer при ховері. all categories не працює.
2) секції книг. між книгами немає відступу.
3) окрема категорія. остання книга завжди перестрибує на новий рядок

2023-08-05 13:28 UTC, Y0less approved these changes
resolved conflict with packages so OK
Better styling posponed for later fixes

2023-08-05 13:29 UTC, Y0less commented
better styling postponed for later

2023-08-05 13:29 UTC, merged